In [1]:
import tensorflow as tf

In [2]:
node1 = tf.constant(3.0, dtype=tf.float32)
node2 = tf.constant(2.0, dtype=tf.float32)

In [3]:
print(node1, node2)

Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)


In [4]:
sess = tf.Session()
sess.run([node1, node2])

[3.0, 2.0]

In [5]:
node3 = tf.add(node1,node2)

In [6]:
sess.run(node3)

5.0

In [7]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [8]:
adder_node = tf.add(a,b)

In [9]:
sess.run(adder_node,{a:4,b:3})

7.0

In [11]:
sess.run(adder_node, {a:[1,2], b:[3,4]})

array([4., 6.], dtype=float32)

In [12]:
W = tf.Variable([0.3], dtype=tf.float32)
b = tf.Variable([-0.3], dtype=tf.float32)

x = tf.placeholder(tf.float32)

linear_model = W*x + b

Instructions for updating:
Colocations handled automatically by placer.


In [13]:
init = tf.global_variables_initializer()
sess.run(init)

In [14]:
sess.run(linear_model, {x:[1,2,3,4]})

array([0.        , 0.3       , 0.6       , 0.90000004], dtype=float32)

## 線形回帰を行う

In [15]:
y = tf.placeholder(tf.float32)
square_delta = tf.square(linear_model - y)
loss = tf.reduce_sum(square_delta)
sess.run(loss, {x:[1,2,3,4], y:[0,-1,-2,-3]})

23.66

In [26]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)
sess.run(init)

for i in range(1000):
    sess.run(train, {x:[1,2,3,4], y:[0,-1,-2,-3]})
    if i % 100 == 0:
        weight = sess.run([W])
        print('W:{}'.format(weight))
sess.run([W,b])

W:[array([-0.21999997], dtype=float32)]
W:[array([-0.84270465], dtype=float32)]
W:[array([-0.9528499], dtype=float32)]
W:[array([-0.98586655], dtype=float32)]
W:[array([-0.9957634], dtype=float32)]
W:[array([-0.9987301], dtype=float32)]
W:[array([-0.99961936], dtype=float32)]
W:[array([-0.9998859], dtype=float32)]
W:[array([-0.9999658], dtype=float32)]
W:[array([-0.9999897], dtype=float32)]


[array([-0.9999969], dtype=float32), array([0.9999908], dtype=float32)]

In [23]:
sess.run([W])

[array([-0.84079814], dtype=float32)]

In [24]:
sess.run([b])

[array([0.53192717], dtype=float32)]

In [28]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata("MNIST original")

In [29]:
X = mnist.data
y = mnist.target

In [30]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer() #バイナリーってなんだろ
lb.fit(range(0,10)) #0から10個あると指定する感じかな
y_onehot = lb.transform(y)

In [31]:
import numpy as np

In [32]:
print(y[:10])
print(y[-10:])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]
